name: build
on:
  workflow_dispatch:
jobs:
  build:
    name: Build project
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64
    - name: precheck
      run: |
        set PATH="%PATH%;C:\Program Files (x86)\Windows Kits\10\Tools\x86\ACPIVerify\"
        dir "C:\Program Files (x86)\Windows Kits\10\Tools\x86\"
        iasl.exe -v
