name: build
on:
  workflow_dispatch:
jobs:
  build:
    name: Build project
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'
    - uses: ilammy/setup-nasm@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64
    - name: add iasl to PATH
      run: |
          Add-Content $env:GITHUB_PATH "D:\a\compile\compile\iasl\"
         
    - name: precheck
      run: |
         iasl.exe -v
         set NASM_PREFIX=C:\Users\runneradmin\nasm\
         cd edk2
         edksetup.bat
         echo "-------------------------------------------------"
         build -w -a X64 -t VS2022 -b NOOPT -p MiniVisorPkg\Builds\Platform\EFI\MiniVisorPkg.dsc
         dir /s MiniVisorDxe.efi
      shell: cmd
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: "MiniVisorPkg"
