name: build
on:
  workflow_dispatch:
jobs:
  build:
    name: Build project
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'
    - uses: ilammy/setup-nasm@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64
    - name: find file
      run: |
        Get-ChildItem -Path "C:\" -Filter "*nmake.exe*" -Recurse -ErrorAction SilentlyContinue | Where-Object {$_.PSIsContainer} | Select-Object -ExpandProperty Fullname
