name: download
on:
  workflow_dispatch:
    inputs:
      input1:
        description: project url
        required: true
        type: string
jobs:
  download:
    name: Build project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'
    
    - name: git clone
      run: |
          git clone ${{ github.event.inputs.input1 }}
          git clone -b edk2-stable202111 --recurse-submodules https://github.com/tianocore/edk2
          curl -L -O https://gist.githubusercontent.com/facelordgists/80e868ff5e315878ecd6/raw/d9297bdd07f6105397f34113ef2ddccd95e54461/delete-git-recursively.sh
          chmod 755 delete-git-recursively.sh
          ./delete-git-recursively.sh
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: "MiniVisorPkg"
