name: msbuild
on:
  workflow_dispatch:
    inputs:
      input1:
        description: project url
        required: true
        type: string
jobs:
  build:
    name: Build project
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64
    - name: git clone
      run: |
          git clone ${{ github.event.inputs.input1 }}
          git clone https://github.com/xguerin/tclap.git
    - name: download pugixml
      run: |
          Invoke-WebRequest https://github.com/zeux/pugixml/releases/download/v1.13/pugixml-1.13.zip -OutFile pugixml.zip
          Invoke-WebRequest https://github.com/nlohmann/json/releases/download/v3.11.2/include.zip -OutFile nlohmann.zip

    - name: unzip pugixml
      run: |
          Expand-Archive pugixml.zip -DestinationPath . -Force
          Expand-Archive nlohmann.zip -DestinationPath . -Force
          

    - name: copu pugixml
      run: |
          mkdir c:\temp\Include\
          mkdir .\wincon\ThirdParty\pugixml\src
          Copy-Item -Path .\pugixml-1.13\src\*  -Destination c:\temp\Include\
          Copy-Item -Path .\single_include\*  -Destination c:\temp\Include\
          Copy-Item -Path .\tclap  -Destination .\wincon\ThirdParty\ -Recurse
          Copy-Item -Path .\pugixml-1.13\src\*  -Destination .\wincon\ThirdParty\pugixml\src\ -Recurse
          Copy-Item -Path .\single_include\*  -Destination .\wincon\ThirdParty\ -Recurse
          
          dir .\wincon\ThirdParty\
          Get-ChildItem -Path .\wincon\ThirdParty\ -Recurse -Force -ErrorAction SilentlyContinue | Select-Object FullName

 
     
    - name: Retrieve and build all available solutions
      run: |
          .\Build-AllSamples.ps1 -Verbose
      env:
          WDS_Configuration: ${{ matrix.configuration }}
          WDS_Platform: ${{ matrix.platform }}
          WDS_ReportFileName: _overview.${{ matrix.configuration }}.${{ matrix.platform }}
    - uses: actions/upload-artifact@v3
      with:
          name: Release
          path: |
            **\Release\
    - name: Archive build logs and overview build reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
          name: logs
          path: _logs

