name: msbuild
on:
  workflow_dispatch:
    inputs:
      input1:
        description: project url
        required: true
        type: string
jobs:
  build:
    name: Build project
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64
    - name: git clone
      run: |
          git clone ${{ github.event.inputs.input1  }}
      
    - name: Retrieve and build all available solutions
      run: |
          .\Build-AllSamples.ps1 -Verbose
      env:
          WDS_Configuration: ${{ matrix.configuration }}
          WDS_Platform: ${{ matrix.platform }}
          WDS_ReportFileName: _overview.${{ matrix.configuration }}.${{ matrix.platform }}
    - uses: actions/upload-artifact@v3
      with:
          name: Release
          path: |
            **\Release\
  report:
    name: Generate global report
    runs-on: windows-2022
    needs: build
    if: always()
    steps:

      - name: Retrieve overview reports
        uses: actions/download-artifact@v3
        with:
          name: logs
          path: _logs

      - name: Archive global overview build reports
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: _logs/_overview.all.*
