name: msbuild
on:
  workflow_dispatch:

jobs:
  build:
    name: Build project
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64
    - name: add iasl to PATH
      run: |
          Add-Content $env:GITHUB_PATH "D:\a\compile\compile\iasl\"
          Add-Content $env:GITHUB_PATH "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64  
    - name: Configure build for amd64
      uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
          arch: amd64


 
     
    - name: Retrieve and build all available solutions
      run: |
          .\Build-AllSamples.ps1 -Verbose
      env:
          WDS_Configuration: ${{ matrix.configuration }}
          WDS_Platform: ${{ matrix.platform }}
          WDS_ReportFileName: _overview.${{ matrix.configuration }}.${{ matrix.platform }}
    - uses: actions/upload-artifact@v3
      with:
          name: Release
          path: |
            **\Release\
    - name: Archive build logs and overview build reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
          name: logs
          path: _logs

