name: msbuild
on:
  workflow_dispatch:
    inputs:
      input1:
        description: project url
        required: true
        type: string
jobs:
  build:
    name: Build project
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: git clone
      run: |
          git clone ${{ github.event.inputs.input1  }}
          pip install mercurial_extension_utils
          pip install mercurial_dynamic_username
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
      
    - name: Retrieve and build all available solutions
      run: |
          .\Build-AllSamples.ps1 -Verbose
      env:
          WDS_Configuration: ${{ matrix.configuration }}
          WDS_Platform: ${{ matrix.platform }}
          WDS_ReportFileName: _overview.${{ matrix.configuration }}.${{ matrix.platform }}
    - uses: actions/upload-artifact@v3
      with:
          name: Release
          path: |
            **\Release\
    - name: Archive build logs and overview build reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
          name: logs
          path: _logs

